apiVersion: apps/v1
kind: Deployment
metadata:
  name: sport-app-autorizador-deploy
  labels:
    app: sport-app-autorizador-deploy
  namespace: eks-sport-app
  annotations:
    monitoring: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sport-app-autorizador-deploy
  template:
    metadata:
      labels:
        app: sport-app-autorizador-deploy
    spec:
      containers:
        - name: sport-app-autorizador-deploy
          image: DOCKER_IMAGE
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /autorizador/health/ping
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 60
          resources:
            requests:
              memory: "512Mi"
              cpu: "50m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: pfsecrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: pfsecrets
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: pfsecrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pfsecrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pfsecrets
                  key: DB_PASSWORD
