apiVersion: v1
kind: Service
metadata:
  labels:
    app: sport-app-autorizador-service
  name: sport-app-autorizador-service
  namespace: eks-sport-app
spec:
  selector:
    app: sport-app-autorizador-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
